apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auto-deploy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: armorblox-autodeploy
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: service_pending_queries
      target:
        type: AverageValue
        averageValue: 3
  behavior:
    scaleUp:
      policies:
        - type: Pods
          value: 4
          periodSeconds: 60
      selectPolicy: Min

---